### ISSUE TITLE
Error: a non-empty Access Key (AKID) must be provided in the credential

### ISSUE THREAD

**Issue by mmangiante** [stefansundin/s3verify#1]
I launched the command in this format as suggested in the usage part of README.md:

s3verify.exe E:\vm-oemsan\vm-oemsan-disk1.vmdk s3://xxxxxxxx/vm-oemsan/vm-oemsan-disk1.vmdk

and obtained this error:

`Fetching S3 object information...
operation error S3: GetBucketLocation, https response error StatusCode: 400, RequestID: A63K84RQFV4XMH30, HostID: 60ykfoUbKUYP38DuSfRbuyZtiQLofSPHQ9lcQKOeiYcNXhoVT6jF9v4P0tfMG12fpdQMYJeX4Vk=, api error AuthorizationHeaderMalformed: The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential.`

I've seen the help and I can't find any option related to non-empty Access Key.

I used the binary s3verify included in s3verify-0.1.0-windows_amd64.zip

**Comment by mmangiante** [comment]
Resolved, I recreated my default profile and now it works.

**Comment by stefansundin** [comment]
Hello.

Interesting. Is this object publicly readable? I think `--no-sign-request` might help you if that is the case.

I'll take a look at this and try to improve the experience. The error message should be better if anything.

Thanks for reporting the issue.

**Comment by stefansundin** [comment]
I pushed a change that prints the following if no AWS credentials can be found:

```
Warning: AWS credentials were not found. Please set up your AWS credentials.
```

I did some testing and it doesn't seem possible to grant access to `s3:GetObjectAttributes` for completely anonymous requests, so I also updated the explanation for the `--no-sign-request` argument. Completely anonymous access could be possible on other S3-compatible APIs, which is why I didn't remove the argument.

These changes are not enough to release a new version but will be included in the next version, but you can install them using `go install` as described in the README.
